// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as constants$0 from "../constants/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates checks for updates
 */
export function CheckForUpdates(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2701935820) as any;
    return $resultPromise;
}

/**
 * GetAppInfo 获取应用程序信息（类似VSCode的关于页面）
 */
export function GetAppInfo(): Promise<$models.AppInfo | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(714048766) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetConfig retrieves the configuration file content
 */
export function GetConfig(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1500926409) as any;
    return $resultPromise;
}

/**
 * GetConfigValue 根据YAML路径获取配置值
 * 支持路径如: "ping.interval", "interval", "ping.count" 等
 */
export function GetConfigValue(path: string): Promise<any> & { cancel(): void } {
    let $resultPromise = $Call.ByID(797097686, path) as any;
    return $resultPromise;
}

export function GetCurrentInstanceInfo(): Promise<{ [_: string]: any }> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3707045995) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetFrontendConfig 获取前端需要的配置信息
 * 只返回前端实际使用的配置项，而不是完整的配置文件
 */
export function GetFrontendConfig(): Promise<$models.FrontendConfig | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1098278021) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetHistoryWithHosts 获取主机历史数据
 */
export function GetHistoryWithHosts(hosts: string[], startTime: number, endTime: number, step: number): Promise<types$0.HostsRangeResponse | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2495755216, hosts, startTime, endTime, step) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetHosts retrieves the list of hosts
 */
export function GetHosts(page: number, pageSize: number, searchTerm: string): Promise<types$0.HostsResponse | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2747365634, page, pageSize, searchTerm) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType8($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetLogFileContent retrieves the content of a specific log file
 */
export function GetLogFileContent(fileName: string, ...isLatest: boolean[]): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2764732514, fileName, isLatest) as any;
    return $resultPromise;
}

/**
 * GetLogFiles retrieves the list of log files with their details
 */
export function GetLogFiles(): Promise<types$0.LogFileInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2219189890) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType10($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetSharedConstant retrieves shared constants
 */
export function GetSharedConstant(): Promise<constants$0.SharedConstants | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2539832674) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType12($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetStatusWithHosts retrieves latency data and status for hosts
 */
export function GetStatusWithHosts(hosts: string[]): Promise<types$0.HostsStatusResponse | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2962638184, hosts) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType14($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * RestartApp restarts the application
 */
export function RestartApp(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(579549339) as any;
    return $resultPromise;
}

/**
 * SaveConfig saves the configuration file content
 */
export function SaveConfig(content: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3220636282, content) as any;
    return $resultPromise;
}

/**
 * Shutdown is called when the service shuts down
 */
export function ServiceShutdown(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3322109826, options) as any;
    return $resultPromise;
}

/**
 * Startup is called when the service starts
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1326445753, options) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.FrontendConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = types$0.HostsRangeResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = types$0.HostsResponse.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = types$0.LogFileInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = constants$0.SharedConstants.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = types$0.HostsStatusResponse.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
