// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as constants$0 from "../constants/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CheckForUpdates checks for updates
 * @returns {Promise<string> & { cancel(): void }}
 */
export function CheckForUpdates() {
    let $resultPromise = /** @type {any} */($Call.ByID(2701935820));
    return $resultPromise;
}

/**
 * GetConfig retrieves the configuration file content
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetConfig() {
    let $resultPromise = /** @type {any} */($Call.ByID(1500926409));
    return $resultPromise;
}

/**
 * @returns {Promise<{ [_: string]: any }> & { cancel(): void }}
 */
export function GetCurrentInstanceInfo() {
    let $resultPromise = /** @type {any} */($Call.ByID(3707045995));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetHosts retrieves the list of hosts
 * @param {number} page
 * @param {number} pageSize
 * @param {string} searchTerm
 * @returns {Promise<types$0.HostsResponse | null> & { cancel(): void }}
 */
export function GetHosts(page, pageSize, searchTerm) {
    let $resultPromise = /** @type {any} */($Call.ByID(2747365634, page, pageSize, searchTerm));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetLatencyWithHosts retrieves latency data for hosts
 * @param {string[]} hosts
 * @returns {Promise<types$0.HostsLatencyResponse | null> & { cancel(): void }}
 */
export function GetLatencyWithHosts(hosts) {
    let $resultPromise = /** @type {any} */($Call.ByID(2388114338, hosts));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetSharedConstant retrieves shared constants
 * @returns {Promise<constants$0.SharedConstants | null> & { cancel(): void }}
 */
export function GetSharedConstant() {
    let $resultPromise = /** @type {any} */($Call.ByID(2539832674));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType6($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * RestartApp restarts the application
 * @returns {Promise<void> & { cancel(): void }}
 */
export function RestartApp() {
    let $resultPromise = /** @type {any} */($Call.ByID(579549339));
    return $resultPromise;
}

/**
 * SaveConfig saves the configuration file content
 * @param {string} content
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveConfig(content) {
    let $resultPromise = /** @type {any} */($Call.ByID(3220636282, content));
    return $resultPromise;
}

/**
 * Shutdown is called when the service shuts down
 * @param {application$0.ServiceOptions} options
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ServiceShutdown(options) {
    let $resultPromise = /** @type {any} */($Call.ByID(3322109826, options));
    return $resultPromise;
}

/**
 * Startup is called when the service starts
 * @param {application$0.ServiceOptions} options
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ServiceStartup(options) {
    let $resultPromise = /** @type {any} */($Call.ByID(1326445753, options));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = types$0.HostsResponse.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = types$0.HostsLatencyResponse.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = constants$0.SharedConstants.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
