// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as constants$0 from "../constants/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates checks for updates
 */
export function CheckForUpdates(): $CancellablePromise<string> {
    return $Call.ByID(2701935820);
}

/**
 * DisableAutoStart 禁用开机自启
 */
export function DisableAutoStart(): $CancellablePromise<void> {
    return $Call.ByID(3967391688);
}

/**
 * EnableAutoStart 启用开机自启
 */
export function EnableAutoStart(): $CancellablePromise<void> {
    return $Call.ByID(1596571863);
}

/**
 * GetAppInfo 获取应用程序信息（类似VSCode的关于页面）
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo | null> {
    return $Call.ByID(714048766).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAutoStartInfo 获取开机自启的详细信息
 */
export function GetAutoStartInfo(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(2034989824).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetConfig retrieves the configuration file content
 */
export function GetConfig(): $CancellablePromise<string> {
    return $Call.ByID(1500926409);
}

/**
 * GetConfigValue 根据YAML路径获取配置值
 * 支持路径如: "ping.interval", "interval", "ping.count" 等
 */
export function GetConfigValue(path: string): $CancellablePromise<any> {
    return $Call.ByID(797097686, path);
}

export function GetCurrentInstanceInfo(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(3707045995).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetFrontendConfig 获取前端需要的配置信息
 * 只返回前端实际使用的配置项，而不是完整的配置文件
 */
export function GetFrontendConfig(): $CancellablePromise<$models.FrontendConfig | null> {
    return $Call.ByID(1098278021).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetHistoryWithHosts 获取主机历史数据
 */
export function GetHistoryWithHosts(hosts: string[], startTime: number, endTime: number, step: number): $CancellablePromise<types$0.HostsRangeResponse | null> {
    return $Call.ByID(2495755216, hosts, startTime, endTime, step).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetHosts retrieves the list of hosts
 */
export function GetHosts(page: number, pageSize: number, searchTerm: string): $CancellablePromise<types$0.HostsResponse | null> {
    return $Call.ByID(2747365634, page, pageSize, searchTerm).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetLogFileContent retrieves the content of a specific log file
 */
export function GetLogFileContent(fileName: string, ...isLatest: boolean[]): $CancellablePromise<string> {
    return $Call.ByID(2764732514, fileName, isLatest);
}

/**
 * GetLogFiles retrieves the list of log files with their details
 */
export function GetLogFiles(): $CancellablePromise<types$0.LogFileInfo[]> {
    return $Call.ByID(2219189890).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetSharedConstant retrieves shared constants
 */
export function GetSharedConstant(): $CancellablePromise<constants$0.SharedConstants | null> {
    return $Call.ByID(2539832674).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetStatusWithHosts retrieves latency data and status for hosts
 */
export function GetStatusWithHosts(hosts: string[]): $CancellablePromise<types$0.HostsStatusResponse | null> {
    return $Call.ByID(2962638184, hosts).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * IsAutoStartEnabled 检查开机自启是否已启用
 */
export function IsAutoStartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(581220391);
}

/**
 * RestartApp restarts the application
 */
export function RestartApp(): $CancellablePromise<void> {
    return $Call.ByID(579549339);
}

/**
 * SaveConfig saves the configuration file content
 */
export function SaveConfig(content: string): $CancellablePromise<void> {
    return $Call.ByID(3220636282, content);
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.FrontendConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = types$0.HostsRangeResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = types$0.HostsResponse.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = types$0.LogFileInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = constants$0.SharedConstants.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = types$0.HostsStatusResponse.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
