// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * PlatformInfo 定义平台信息
 */
export class PlatformInfo {
    "os": string;
    "arch": string;

    /** Creates a new PlatformInfo instance. */
    constructor($$source: Partial<PlatformInfo> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformInfo($$parsedSource as Partial<PlatformInfo>);
    }
}

/**
 * SharedConstants 定义需要共享的常量
 */
export class SharedConstants {
    "appName": string;
    "appVersion": string;
    "platformInfo": PlatformInfo;
    "UpdateServer": string;
    "needsRestart": boolean;

    /** Creates a new SharedConstants instance. */
    constructor($$source: Partial<SharedConstants> = {}) {
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("platformInfo" in $$source)) {
            this["platformInfo"] = (new PlatformInfo());
        }
        if (!("UpdateServer" in $$source)) {
            this["UpdateServer"] = "";
        }
        if (!("needsRestart" in $$source)) {
            this["needsRestart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharedConstants instance from a string or object.
     */
    static createFrom($$source: any = {}): SharedConstants {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("platformInfo" in $$parsedSource) {
            $$parsedSource["platformInfo"] = $$createField2_0($$parsedSource["platformInfo"]);
        }
        return new SharedConstants($$parsedSource as Partial<SharedConstants>);
    }
}

// Private type creation functions
const $$createType0 = PlatformInfo.createFrom;
