// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HeartbeatConfig 定义心跳配置
 */
export class HeartbeatConfig {
    "enabled": boolean;

    /**
     * 秒
     */
    "interval": number;

    /**
     * 秒
     */
    "timeout": number;

    /** Creates a new HeartbeatConfig instance. */
    constructor($$source: Partial<HeartbeatConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("interval" in $$source)) {
            this["interval"] = 0;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeartbeatConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): HeartbeatConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeartbeatConfig($$parsedSource as Partial<HeartbeatConfig>);
    }
}

/**
 * PlatformInfo 定义平台信息
 */
export class PlatformInfo {
    "os": string;
    "arch": string;

    /** Creates a new PlatformInfo instance. */
    constructor($$source: Partial<PlatformInfo> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformInfo($$parsedSource as Partial<PlatformInfo>);
    }
}

/**
 * ServerConfig 定义服务器配置
 */
export class ServerConfig {
    "baseUrl": string;
    "updateApi": string;
    "heartbeatApi": string;

    /** Creates a new ServerConfig instance. */
    constructor($$source: Partial<ServerConfig> = {}) {
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("updateApi" in $$source)) {
            this["updateApi"] = "";
        }
        if (!("heartbeatApi" in $$source)) {
            this["heartbeatApi"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig($$parsedSource as Partial<ServerConfig>);
    }
}

/**
 * SharedConstants 定义需要共享的常量
 */
export class SharedConstants {
    "appName": string;
    "appVersion": string;
    "platformInfo": PlatformInfo;
    "server": ServerConfig;
    "heartbeat": HeartbeatConfig;
    "needsRestart": boolean;

    /** Creates a new SharedConstants instance. */
    constructor($$source: Partial<SharedConstants> = {}) {
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("platformInfo" in $$source)) {
            this["platformInfo"] = (new PlatformInfo());
        }
        if (!("server" in $$source)) {
            this["server"] = (new ServerConfig());
        }
        if (!("heartbeat" in $$source)) {
            this["heartbeat"] = (new HeartbeatConfig());
        }
        if (!("needsRestart" in $$source)) {
            this["needsRestart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharedConstants instance from a string or object.
     */
    static createFrom($$source: any = {}): SharedConstants {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("platformInfo" in $$parsedSource) {
            $$parsedSource["platformInfo"] = $$createField2_0($$parsedSource["platformInfo"]);
        }
        if ("server" in $$parsedSource) {
            $$parsedSource["server"] = $$createField3_0($$parsedSource["server"]);
        }
        if ("heartbeat" in $$parsedSource) {
            $$parsedSource["heartbeat"] = $$createField4_0($$parsedSource["heartbeat"]);
        }
        return new SharedConstants($$parsedSource as Partial<SharedConstants>);
    }
}

// Private type creation functions
const $$createType0 = PlatformInfo.createFrom;
const $$createType1 = ServerConfig.createFrom;
const $$createType2 = HeartbeatConfig.createFrom;
