// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * PlatformInfo 定义平台信息
 */
export class PlatformInfo {
    /**
     * Creates a new PlatformInfo instance.
     * @param {Partial<PlatformInfo>} [$$source = {}] - The source object to create the PlatformInfo.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlatformInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformInfo(/** @type {Partial<PlatformInfo>} */($$parsedSource));
    }
}

/**
 * SharedConstants 定义需要共享的常量
 */
export class SharedConstants {
    /**
     * Creates a new SharedConstants instance.
     * @param {Partial<SharedConstants>} [$$source = {}] - The source object to create the SharedConstants.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (!("platformInfo" in $$source)) {
            /**
             * @member
             * @type {PlatformInfo}
             */
            this["platformInfo"] = (new PlatformInfo());
        }
        if (!("UpdateServer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdateServer"] = "";
        }
        if (!("needsRestart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsRestart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharedConstants instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SharedConstants}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("platformInfo" in $$parsedSource) {
            $$parsedSource["platformInfo"] = $$createField2_0($$parsedSource["platformInfo"]);
        }
        return new SharedConstants(/** @type {Partial<SharedConstants>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PlatformInfo.createFrom;
