// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHosts(arg1, arg2) {
  return window['go']['main']['App']['GetHosts'](arg1, arg2);
}

export function GetLatencyWithHosts(arg1) {
  return window['go']['main']['App']['GetLatencyWithHosts'](arg1);
}

export function GetSharedConstant() {
  return window['go']['main']['App']['GetSharedConstant']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
