// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {constants} from '../models';

export function CheckForUpdates():Promise<string>;

export function GetConfig():Promise<string>;

export function GetHosts(arg1:number,arg2:number):Promise<types.HostsResponse>;

export function GetLatencyWithHosts(arg1:Array<string>):Promise<types.HostsLatencyResponse>;

export function GetSharedConstant():Promise<constants.SharedConstants>;

export function RestartApp():Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;
