// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {constants} from '../models';

export function CheckForUpdates():Promise<string>;

export function GetConfig():Promise<string>;

export function GetSharedConstant():Promise<constants.SharedConstants>;

export function SaveConfig(arg1:string):Promise<void>;
