// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ServiceOptions {
    /**
     * Creates a new ServiceOptions instance.
     * @param {Partial<ServiceOptions>} [$$source = {}] - The source object to create the ServiceOptions.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * Name can be set to override the name of the service
             * This is useful for logging and debugging purposes
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Route" in $$source)) {
            /**
             * Route is the path to the assets
             * @member
             * @type {string}
             */
            this["Route"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceOptions(/** @type {Partial<ServiceOptions>} */($$parsedSource));
    }
}
