// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ServiceOptions {
    /**
     * Name can be set to override the name of the service
     * This is useful for logging and debugging purposes
     */
    "Name": string;

    /**
     * Route is the path to the assets
     */
    "Route": string;

    /** Creates a new ServiceOptions instance. */
    constructor($$source: Partial<ServiceOptions> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Route" in $$source)) {
            this["Route"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceOptions($$parsedSource as Partial<ServiceOptions>);
    }
}
